services:
    _defaults:
        autowire: true

    Tuscanicz\DateTimeBundle\DateIntervalFactory:

    Tuscanicz\DateTimeBundle\DateTimeFactory:
        arguments:
            - '%tuscanicz_datetime.app_timezone%'
